---
- name: Add MongoDB repository key for Ubuntu
  apt_key:
    url: "https://www.mongodb.org/static/pgp/server-{{ mongodb_version }}.asc"
    state: present

- name: Add MongoDB repository for Ubuntu
  template:
    src: mongodb.repo.j2
    dest: /etc/apt/sources.list.d/mongodb.list
    owner: root
    group: root
    mode: 0644

- name: Install MongoDB on Ubuntu
  apt:
    name: mongodb-org
    state: present

- name: Start MongoDB service on Ubuntu
  ansible.builtin.service:
    name: mongod
    state: started
    enabled: yes
